### PR TITLE
src/Boolector.hs: add MonadFail instances

### PR DESCRIPTION
**Pull request by vaibhavsagar**
Without this change, the test suite for this package fails to compile on GHC 8.6.4.

### CODE REVIEW

**Comment by deian** [comment]
This looks great, any chance you can just remove version check? We might as well just do this across the board

**Comment by vaibhavsagar** [comment]
`MonadFail` isn't available before `base-4.9.0.0`, so would you like me to import [`fail`](http://hackage.haskell.org/package/fail) and conditionally depend on that, or are you saying you're okay with dropping support for GHC < 8.0?

**Comment by vaibhavsagar** [comment]
I've chosen to go with the first approach.

**Comment by deian** [comment]
Sorry I thought I merged yesterday. Honestly all the options seemed fine! Thanks!

**Comment by vaibhavsagar** [comment]
My pleasure!

**Pull request merged**
